/**
 * Smoke test for the generated registry manifest. Guards against generator
 * regressions: schema version, per-tier shape, presence of indexes, and the
 * invariant that `internal` exports never leak into the public manifest.
 *
 * Runs in the `node` Vitest project. The registry is generated by
 * `npm run build:registry`, which is invoked by `npm run build` and by
 * `check:agent-ready`. If the file is missing locally (e.g. `npm test`
 * without a build), the test self-skips — CI always builds first so this
 * will run in any real signal-producing pipeline.
 */
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { describe, expect, it } from 'vitest'

import { REGISTRY_SCHEMA_VERSION } from '../../../scripts/registry-types'

const REGISTRY_PATH = resolve(__dirname, '../../../dist/registry.json')

const registryExists = existsSync(REGISTRY_PATH)

const describeRegistry = registryExists ? describe : describe.skip

if (!registryExists) {
  console.warn(
    `[registry.test] dist/registry.json missing — skipping. Run ` +
      `\`npm run build:registry --workspace @tetherto/mdk-react-devkit\` to enable.`,
  )
}

describeRegistry('dist/registry.json', () => {
  const registry = registryExists
    ? (JSON.parse(readFileSync(REGISTRY_PATH, 'utf8')) as Record<string, unknown>)
    : ({} as Record<string, unknown>)

  it('declares the current schema version', () => {
    expect(registry.version).toBe(REGISTRY_SCHEMA_VERSION)
  })

  it('describes @tetherto/mdk-react-devkit', () => {
    expect(registry.package).toBe('@tetherto/mdk-react-devkit')
  })

  it('ships components and hooks arrays', () => {
    expect(Array.isArray(registry.components)).toBe(true)
    expect(Array.isArray(registry.hooks)).toBe(true)
  })

  it('ships O(1) lookup indexes', () => {
    expect(registry.indexes).toBeDefined()
    const idx = registry.indexes as Record<string, unknown>
    for (const key of [
      'componentsByName',
      'hooksByName',
      'componentsByCategory',
      'componentsByDomain',
      'componentsByKernelCapability',
      'componentsByTier',
    ]) {
      expect(idx[key], `index.${key} should be present`).toBeDefined()
    }
  })

  it('never leaks `internal` entries into the public manifest', () => {
    const components = registry.components as Array<{ tier?: string }>
    const hooks = registry.hooks as Array<{ tier?: string }>
    expect(components.every((c) => c.tier !== 'internal')).toBe(true)
    expect(hooks.every((h) => h.tier !== 'internal')).toBe(true)
  })

  it('has at least one agent-ready component (sanity)', () => {
    const components = registry.components as Array<{ tier?: string }>
    expect(components.filter((c) => c.tier === 'agent-ready').length).toBeGreaterThan(0)
  })

  it('agent-ready components reference `USAGE.md` and at least one example', () => {
    const components = registry.components as Array<{
      tier?: string
      name: string
      usageDoc?: string
      examples?: string[]
    }>
    const broken = components
      .filter((c) => c.tier === 'agent-ready')
      .filter((c) => !c.usageDoc || !c.examples || c.examples.length === 0)
    expect(
      broken,
      `Agent-ready without docs/examples: ${broken.map((c) => c.name).join(', ')}`,
    ).toEqual([])
  })

  it('stamps generation provenance (1.4.0)', () => {
    const generatedFrom = registry.generatedFrom as { gitSha: string | null } | undefined
    expect(generatedFrom).toBeDefined()
    // Built from a git checkout in dev/CI — a 40-char sha; null only for tarball builds.
    if (generatedFrom!.gitSha !== null) {
      expect(generatedFrom!.gitSha).toMatch(/^[0-9a-f]{40}$/)
    }
  })

  it('emits descriptionFull only when it differs from the truncated description', () => {
    const components = registry.components as Array<{
      name: string
      description: string
      descriptionFull?: string
      props: Array<{ name: string; description?: string; descriptionFull?: string }>
    }>
    const hooks = registry.hooks as Array<{
      name: string
      description: string
      descriptionFull?: string
    }>
    for (const entry of [...components, ...hooks]) {
      if (entry.descriptionFull !== undefined) {
        expect(entry.descriptionFull, `${entry.name}.descriptionFull`).not.toBe(entry.description)
        expect(entry.descriptionFull.length).toBeGreaterThan(0)
      }
    }
    for (const c of components) {
      for (const p of c.props) {
        if (p.descriptionFull !== undefined) {
          expect(p.descriptionFull, `${c.name}.${p.name}.descriptionFull`).not.toBe(p.description)
        }
      }
    }
  })

  it('componentsByName index points back to the right entries', () => {
    const components = registry.components as Array<{ name: string }>
    const byName = (registry.indexes as { componentsByName: Record<string, number> })
      .componentsByName
    for (const [name, idx] of Object.entries(byName)) {
      expect(components[idx]?.name).toBe(name)
    }
  })
})
