import type { DocsMeta } from './docs-data.js'

/**
 * The README emitted into the generated dataset directory. Tells the doc
 * writer what each file is, how to embed the rendering components, and how to
 * check for drift. Excluded from drift comparison (it carries the volatile
 * version stamp).
 */
export const buildReadme = (meta: DocsMeta): string => {
  const { generatedFrom: g } = meta
  return `# Generated docs data — DO NOT EDIT BY HAND

This directory is generated by \`mdk-ui docs:build\` from the MDK component
registry. Re-run that command to refresh it; never edit these files directly.

- **Source:** \`${g.package}@${g.packageVersion}\` (registry schema ${g.registrySchema})
- **Built from commit:** \`${g.gitSha ?? 'unknown (non-git build)'}\`
- **Dataset schema:** ${meta.schemaVersion}
- **Version label:** ${meta.versionLabel}
- **Components:** ${meta.counts.components} · **Hooks:** ${meta.counts.hooks} · **Stores:** ${meta.counts.stores} · **Query helpers:** ${meta.counts.queryHelpers} · **Usage docs:** ${meta.counts.usageDocs} · **Examples:** ${meta.counts.examples}

## Files

| File | What it is |
| --- | --- |
| \`components.json\` | Component catalog: name, sub-package, tier, category, full description, props (name / type / required / default / description), and pointers to usage + example files. |
| \`hooks.json\` | Hook catalog spanning both packages: name, \`package\` (\`react-devkit\` \| \`react-adapter\`), tier, category, full description, signature, and (adapter hooks) \`requiresProvider\`. |
| \`stores.json\` | ui-foundation surface: \`{ stores, queryHelpers, utilities }\`. Each store lists its category, factory, state fields, and actions; each query helper its signature + category; each utility its kind (function/constant), signature, and category. |
| \`fonts.json\` | \`@tetherto/mdk-fonts\` package surface: import specifiers + available font-weight assets. Omitted when no fonts manifest is resolved. |
| \`usage/<Name>.md\` | The component's co-located \`USAGE.md\`, verbatim. |
| \`examples/<Name>/*.tsx.txt\` | Runnable example sources (\`.txt\` so the docs app's tsc/eslint ignore them). |
| \`cli.json\` | The \`mdk-ui\` CLI reference (every command + option). |
| \`meta.json\` | Provenance stamp (source version + git commit). |

## How to use it in a page

After registering the rendering components once in \`src/mdx-components.tsx\`,
embed them in any curated MDX page:

\`\`\`mdx
<ComponentDoc name="LineChartCard" />   {/* description + import + props + usage + examples */}
<PropsTable name="BarChart" />          {/* just the props table */}
\`\`\`

Keep your hand-written prose, headings, and page grouping — the components
only render the parts that go stale.

## Checking for drift

To see whether this committed data still matches the current code, re-run with
\`--report-only\` (from the MDK monorepo, against a freshly built registry):

\`\`\`bash
mdk-ui docs:build --docs-repo <this-repo> --report-only
\`\`\`

It prints a field-level diff and exits non-zero when the data is stale. Re-run
without \`--report-only\` to refresh, then review and commit the diff.
`
}
