/**
 * Pre-seeded page — ships with the mdk-ui-shell template but is removable.
 * Carries the marker below (do not delete) so the CLI treats this like a file
 * generated by `mdk-ui add page`, i.e. `mdk-ui remove page Explorer`
 * unscaffolds it cleanly without needing `--force`.
 */
import {
  DEVICE_EXPLORER_DEVICE_TYPE,
  DeviceExplorer,
  EmptyState,
  ExplorerDetail,
  ExplorerLayout,
  useExplorerData,
  useExplorerSelection,
} from '@tetherto/mdk-react-devkit'
import type {
  DataTableRowSelectionState,
  DeviceExplorerDeviceType,
  LocalFilters,
} from '@tetherto/mdk-react-devkit'
import { useMemo, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'

import { PageLayout } from '../components/PageLayout'

const ExplorerPage = () => {
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const [deviceType, setDeviceType] = useState<DeviceExplorerDeviceType>(
    DEVICE_EXPLORER_DEVICE_TYPE.CONTAINER,
  )
  const [searchTags, setSearchTags] = useState<string[]>([])
  const [filters, setFilters] = useState<LocalFilters>({})
  const [selected, setSelected] = useState<DataTableRowSelectionState>({})

  // Search / status-filter / sort are client-side over a tag-filtered fetch —
  // this mirrors MOS (BE-side paging is tracked separately with management).
  const { data, searchOptions, filterOptions } = useExplorerData({
    deviceType,
    searchTags,
    filters,
  })

  // A `?thing=<id>` deep-link (e.g. a Site Overview container card click) is
  // treated as a selection too, so it drives the same store-backed panel.
  const deepLinkId = searchParams.get('thing') ?? undefined
  const effectiveSelected = useMemo<DataTableRowSelectionState>(
    () => (deepLinkId ? { ...selected, [deepLinkId]: true } : selected),
    [selected, deepLinkId],
  )

  // Bridge the table selection into `devicesStore` so the write-control cards
  // (Batch Container Controls, etc.) read it. Resets on tab/selection change.
  useExplorerSelection({
    deviceType,
    rows: data,
    selected: effectiveSelected,
  })

  const hasSelection = Object.values(effectiveSelected).some(Boolean)

  // Selections are per-tab (ids differ across container/miner/cabinet); clear
  // them when the tab changes so a stale id can't drive the detail panel.
  const handleDeviceTypeChange = (type: DeviceExplorerDeviceType): void => {
    setDeviceType(type)
    setSelected({})
  }

  const renderDetail = () => {
    if (!hasSelection) {
      return <EmptyState description="Select a row to see its details" />
    }

    // The per-type panel (container / miner / cabinet) is composed by ExplorerDetail.
    return <ExplorerDetail deviceType={deviceType} onNavigate={(path) => void navigate(path)} />
  }

  return (
    <PageLayout title="Explorer" className="mdk-ui-shell-explorer">
      <ExplorerLayout hasSelection={hasSelection} detail={renderDetail()}
        list={
          <DeviceExplorer
            data={data}
            deviceType={deviceType}
            onDeviceTypeChange={handleDeviceTypeChange}
            searchOptions={searchOptions}
            searchTags={searchTags}
            onSearchTagsChange={setSearchTags}
            filterOptions={filterOptions}
            onFiltersChange={setFilters}
            selectedDevices={selected}
            onSelectedDevicesChange={setSelected}
            getFormattedDate={(date: Date) => date.toISOString()}
            renderAction={() => null}
          />
        }
      />
    </PageLayout>
  )
}

export default ExplorerPage
