/**
 * Pre-seeded page — ships with the mdk-ui-shell template but is removable.
 * Carries the marker below (do not delete) so the CLI treats this like a file
 * generated by `mdk-ui add page`, i.e. `mdk-ui remove page PoolManager`
 * unscaffolds it cleanly without needing `--force`.
 */
import {
  useMinerDevices,
  usePoolConfigsData,
  usePoolManagerDashboard,
  useSiteDetailMiners,
  useSitesOverview,
} from '@tetherto/mdk-react-adapter'
import { PoolManager } from '@tetherto/mdk-react-devkit'
import type { Alert, DashboardStats, PoolManagerView } from '@tetherto/mdk-react-devkit'
import { useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'

import { ROUTE_PATHS } from '../constants/routes'
import { PageLayout } from '../components/PageLayout'

const VALID_VIEWS = new Set<PoolManagerView>(['dashboard', 'pools', 'sites-overview', 'miner-explorer', 'site-detail'])

const PoolManagerPage = () => {
  const navigate = useNavigate()
  const [searchParams, setSearchParams] = useSearchParams()

  // Sidebar sub-items set ?view= — validate and fall back to dashboard.
  const viewParam = searchParams.get('view')
  const currentView: PoolManagerView =
    viewParam && VALID_VIEWS.has(viewParam as PoolManagerView)
      ? (viewParam as PoolManagerView)
      : 'dashboard'

  // Keep URL in sync when the user navigates internally (back buttons, dashboard blocks).
  const handleViewChange = (next: PoolManagerView) => {
    if (next === 'dashboard') {
      setSearchParams({}, { replace: true })
    } else {
      setSearchParams({ view: next }, { replace: true })
    }
  }

  // `usePoolConfigsData` returns raw pool rows (`PoolConfigEntry`), field-
  // identical to the devkit's `PoolConfigData`. `useMinerDevices` fetches miners
  // from `list-things` (tag `t-miner`) in the nested `Device` shape the devkit
  // Miner Explorer expects (so pool names resolve) — same source as the reference app.
  // `useSitesOverview` merges the container sources into display-ready units
  // (+ the raw rows for Site Detail). `usePoolManagerDashboard` shapes the
  // landing stats + recent-alerts feed; the casts are cross-package type bridges.
  const { data: poolConfig } = usePoolConfigsData()
  const { data: miners, isLoading: isMinersLoading } = useMinerDevices()
  const sites = useSitesOverview()
  const dashboard = usePoolManagerDashboard()

  const [selectedUnitId, setSelectedUnitId] = useState<string | null>(null)
  const { connectedMiners } = useSiteDetailMiners(selectedUnitId)

  // Site Detail wiring: feed the miners assigned to the selected container into
  // Site Detail so it shows live connected-miner data. (PDU socket layouts still
  // require a dedicated per-container PDU hook — a follow-up.)
  const siteDetailDataOptions = selectedUnitId
    ? { connectedMiners, actualMinersCount: connectedMiners.length }
    : undefined

  return (
    <PageLayout title="Pool Manager" className="mdk-ui-shell-pool-manager">
      <PoolManager
        poolConfig={poolConfig ?? []}
        miners={miners}
        units={sites.units}
        siteDevices={sites.rawUnits}
        isSitesLoading={sites.isLoading}
        sitesError={sites.error}
        stats={dashboard.stats as DashboardStats}
        isStatsLoading={dashboard.isLoading}
        alerts={dashboard.alerts as Alert[]}
        onViewAllAlerts={() => void navigate(ROUTE_PATHS.ALERTS)}
        view={currentView}
        onViewChange={handleViewChange}
        onSiteSelect={setSelectedUnitId}
        siteDetailDataOptions={siteDetailDataOptions}
        isSiteDetailLoading={!!selectedUnitId && isMinersLoading}
      />
    </PageLayout>
  )
}

export default PoolManagerPage
