/**
 * Pre-seeded page — ships with the mdk-ui-shell template but is removable.
 * Carries the marker below (do not delete) so the CLI treats this like a file
 * generated by `mdk-ui add page`, i.e. `mdk-ui remove page SiteOverview`
 * unscaffolds it cleanly without needing `--force`.
 */
import { ContainerWidgets, useContainerWidgetsData } from '@tetherto/mdk-react-devkit'
import { useNavigate } from 'react-router-dom'

import { PageLayout } from '../components/PageLayout'

const SiteOverviewPage = () => {
  const { containers, isLoading, errorMessage } = useContainerWidgetsData()
  const navigate = useNavigate()

  // Cards are clickable (border/chamfer light up orange on hover). For now a
  // click routes to Explorer with the container id as `thing`.
  // TODO(MDK Op Centre #9): deep-link straight to the container detail once the
  // Explorer detail slice consumes `thing`.
  const handleContainerClick = (id: string): void => {
    navigate(`/explorer?thing=${encodeURIComponent(id)}`)
  }

  return (
    <PageLayout title="Site Overview">
      <ContainerWidgets
        containers={containers}
        isLoading={isLoading}
        errorMessage={errorMessage}
        onContainerClick={handleContainerClick}
      />
    </PageLayout>
  )
}

export default SiteOverviewPage
