/**
 * <FontsDoc />
 *
 * Renders the `@tetherto/mdk-fonts` package surface from the generated docs
 * dataset: the import specifiers a consumer uses and the available font weights.
 * Installed into the mdk-docs repo by `mdk-ui docs:build`; do not edit it there
 * by hand — re-run the command to pick up template changes.
 *
 * Data source: `src/data/<version>/generated/fonts.json` (the active version is
 * read from `src/data/active-version.ts`, regenerated by `docs:build`). This is a
 * React Server Component — it reads the JSON off disk at build time.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

import { DynamicCodeBlock } from "fumadocs-ui/components/dynamic-codeblock";

import { ACTIVE_DOCS_VERSION } from "../data/active-version";

const GENERATED_DIR = join(process.cwd(), "src", "data", ACTIVE_DOCS_VERSION, "generated");

type GeneratedFonts = {
  package: string;
  packageVersion: string;
  description: string;
  imports: string[];
  assets: Array<{ weight: string; file: string }>;
};

const loadFonts = (): GeneratedFonts | null => {
  const abs = join(GENERATED_DIR, "fonts.json");
  if (!existsSync(abs)) return null;
  return JSON.parse(readFileSync(abs, "utf8")) as GeneratedFonts;
};

/** The CSS import is the primary entry point; surface it first. */
const cssImport = (imports: string[]): string | undefined =>
  imports.find((i) => i.endsWith(".css"));

export function FontsDoc() {
  const fonts = loadFonts();

  if (!fonts) {
    return (
      <p>
        <em>
          No generated data for the fonts package. Re-run{" "}
          <code>mdk-ui docs:build</code> with the fonts package available.
        </em>
      </p>
    );
  }

  const css = cssImport(fonts.imports);

  return (
    <div className="mdk-fonts-doc">
      {fonts.description ? <p>{fonts.description}</p> : null}

      {css ? (
        <>
          <h3>Import</h3>
          <DynamicCodeBlock lang="ts" code={`import "${css}";`} />
        </>
      ) : null}

      {fonts.assets.length > 0 ? (
        <>
          <h3>Weights</h3>
          <table>
            <thead>
              <tr>
                <th>Weight</th>
                <th>Asset</th>
              </tr>
            </thead>
            <tbody>
              {fonts.assets.map((a) => (
                <tr key={a.file}>
                  <td>{a.weight}</td>
                  <td>
                    <code>{a.file}</code>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </>
      ) : null}
    </div>
  );
}

export default FontsDoc;
