/**
 * <HookDoc name="useAuth" />
 *
 * Renders the reference block for a single hook from the generated docs dataset:
 * description, source package, import line, call signature, and whether it must
 * run inside `<MdkProvider>`. Installed into the mdk-docs repo by
 * `mdk-ui docs:build`; do not edit it there by hand — re-run the command to pick
 * up template changes.
 *
 * Data source: `src/data/<version>/generated/hooks.json` (the active version is
 * read from `src/data/active-version.ts`, regenerated by `docs:build`). This is a
 * React Server Component — it reads the JSON off disk at build time.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { DynamicCodeBlock } from "fumadocs-ui/components/dynamic-codeblock";

import { ACTIVE_DOCS_VERSION } from "../data/active-version";

const GENERATED_DIR = join(process.cwd(), "src", "data", ACTIVE_DOCS_VERSION, "generated");

/** Map a hook's source package to its import specifier. */
const PACKAGE_IMPORT: Record<string, string> = {
  "react-devkit": "@tetherto/mdk-react-devkit",
  "react-adapter": "@tetherto/mdk-react-adapter",
};

type GeneratedHook = {
  name: string;
  package: "react-devkit" | "react-adapter";
  description: string;
  signature: string;
  requiresProvider?: boolean;
};

const loadHooks = (): GeneratedHook[] => {
  const raw = readFileSync(join(GENERATED_DIR, "hooks.json"), "utf8");
  return JSON.parse(raw) as GeneratedHook[];
};

export function HookDoc({ name }: { name: string }) {
  const hook = loadHooks().find((h) => h.name === name);

  if (!hook) {
    return (
      <p>
        <em>
          No generated data for <code>{name}</code>. Check the name against{" "}
          <code>hooks.json</code>, or re-run <code>mdk-ui docs:build</code>.
        </em>
      </p>
    );
  }

  const importPackage = PACKAGE_IMPORT[hook.package] ?? hook.package;

  return (
    <div className="mdk-hook-doc">
      {hook.description ? <p>{hook.description}</p> : null}

      <DynamicCodeBlock
        lang="tsx"
        code={`import { ${hook.name} } from "${importPackage}";`}
      />

      <h3>Signature</h3>
      <DynamicCodeBlock lang="ts" code={hook.signature} />

      <table>
        <tbody>
          <tr>
            <td>Package</td>
            <td>
              <code>{importPackage}</code>
            </td>
          </tr>
          {hook.package === "react-adapter" ? (
            <tr>
              <td>Requires provider</td>
              <td>{hook.requiresProvider ? "Yes — must run inside <MdkProvider>" : "No"}</td>
            </tr>
          ) : null}
        </tbody>
      </table>
    </div>
  );
}

export default HookDoc;
