/**
 * <QueryHelpersDoc />
 *
 * Renders the full table of ui-foundation query helpers from the generated docs
 * dataset (name, category, signature, description). Installed into the mdk-docs
 * repo by `mdk-ui docs:build`; do not edit it there by hand — re-run the command
 * to pick up template changes.
 *
 * Data source: `src/data/<version>/generated/stores.json` (the active version is
 * read from `src/data/active-version.ts`, regenerated by `docs:build`). This is a
 * React Server Component — it reads the JSON off disk at build time.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { ACTIVE_DOCS_VERSION } from "../data/active-version";

const GENERATED_DIR = join(process.cwd(), "src", "data", ACTIVE_DOCS_VERSION, "generated");

type GeneratedQueryHelper = {
  name: string;
  category: string;
  description: string;
  signature: string;
};

const loadQueryHelpers = (): GeneratedQueryHelper[] => {
  const raw = readFileSync(join(GENERATED_DIR, "stores.json"), "utf8");
  return (JSON.parse(raw) as { queryHelpers?: GeneratedQueryHelper[] }).queryHelpers ?? [];
};

export function QueryHelpersDoc() {
  const helpers = loadQueryHelpers();

  if (helpers.length === 0) {
    return (
      <p>
        <em>No query helpers in the generated dataset.</em>
      </p>
    );
  }

  return (
    <table>
      <thead>
        <tr>
          <th>Helper</th>
          <th>Category</th>
          <th>Signature</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        {helpers.map((h) => (
          <tr key={h.name}>
            <td>
              <code>{h.name}</code>
            </td>
            <td>{h.category}</td>
            <td>
              <code>{h.signature}</code>
            </td>
            <td>{h.description || "—"}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

export default QueryHelpersDoc;
