/**
 * <StoreDoc name="authStore" />
 *
 * Renders the reference block for a single ui-foundation store from the generated docs
 * dataset: description, factory signature, and state + action tables. Installed
 * into the mdk-docs repo by `mdk-ui docs:build`; do not edit it there by hand —
 * re-run the command to pick up template changes.
 *
 * Data source: `src/data/<version>/generated/stores.json` (the active version is
 * read from `src/data/active-version.ts`, regenerated by `docs:build`). This is a
 * React Server Component — it reads the JSON off disk at build time.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { DynamicCodeBlock } from "fumadocs-ui/components/dynamic-codeblock";

import { ACTIVE_DOCS_VERSION } from "../data/active-version";

const GENERATED_DIR = join(process.cwd(), "src", "data", ACTIVE_DOCS_VERSION, "generated");

const IMPORT_PACKAGE = "@tetherto/mdk-ui-foundation";

type StoreField = { name: string; signature: string };

type GeneratedStore = {
  name: string;
  category: string;
  description: string;
  factory: string;
  state: StoreField[];
  actions: StoreField[];
};

const loadStores = (): GeneratedStore[] => {
  const raw = readFileSync(join(GENERATED_DIR, "stores.json"), "utf8");
  return (JSON.parse(raw) as { stores?: GeneratedStore[] }).stores ?? [];
};

function FieldTable({ title, rows }: { title: string; rows: StoreField[] }) {
  if (rows.length === 0) return null;
  return (
    <>
      <h3>{title}</h3>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Signature</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((f) => (
            <tr key={f.name}>
              <td>
                <code>{f.name}</code>
              </td>
              <td>
                <code>{f.signature}</code>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </>
  );
}

export function StoreDoc({ name }: { name: string }) {
  const store = loadStores().find((s) => s.name === name);

  if (!store) {
    return (
      <p>
        <em>
          No generated data for <code>{name}</code>. Check the name against{" "}
          <code>stores.json</code>, or re-run <code>mdk-ui docs:build</code>.
        </em>
      </p>
    );
  }

  return (
    <div className="mdk-store-doc">
      {store.description ? <p>{store.description}</p> : null}

      <DynamicCodeBlock
        lang="tsx"
        code={`import { ${store.factory} } from "${IMPORT_PACKAGE}";`}
      />

      <FieldTable title="State" rows={store.state} />
      <FieldTable title="Actions" rows={store.actions} />
    </div>
  );
}

export default StoreDoc;
