/**
 * <UtilitiesDoc />
 *
 * Renders the public ui-foundation utilities + constants from the generated docs
 * dataset (`./utils`, `./constants`), grouped by category. Installed into the
 * mdk-docs repo by `mdk-ui docs:build`; do not edit it there by hand — re-run
 * the command to pick up template changes.
 *
 * Data source: `src/data/<version>/generated/stores.json` (the active version is
 * read from `src/data/active-version.ts`, regenerated by `docs:build`). This is a
 * React Server Component — it reads the JSON off disk at build time.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { ACTIVE_DOCS_VERSION } from "../data/active-version";

const GENERATED_DIR = join(process.cwd(), "src", "data", ACTIVE_DOCS_VERSION, "generated");

const IMPORT_PACKAGE = "@tetherto/mdk-ui-foundation";

type GeneratedUtility = {
  name: string;
  kind: "function" | "constant";
  category: string;
  description: string;
  signature: string;
};

const loadUtilities = (): GeneratedUtility[] => {
  const raw = readFileSync(join(GENERATED_DIR, "stores.json"), "utf8");
  return (JSON.parse(raw) as { utilities?: GeneratedUtility[] }).utilities ?? [];
};

/** Group utilities by category, preserving sorted order within each group. */
const groupByCategory = (utils: GeneratedUtility[]): Array<[string, GeneratedUtility[]]> => {
  const groups = new Map<string, GeneratedUtility[]>();
  for (const u of utils) {
    const list = groups.get(u.category) ?? [];
    list.push(u);
    groups.set(u.category, list);
  }
  return [...groups.entries()].sort((a, b) => a[0].localeCompare(b[0]));
};

const titleCase = (s: string): string => s.charAt(0).toUpperCase() + s.slice(1);

/**
 * @param kind Optional filter: `"function"` renders only utility functions,
 *   `"constant"` only constants. Omit to render everything with a Kind column.
 */
export function UtilitiesDoc({ kind }: { kind?: "function" | "constant" } = {}) {
  const utilities = loadUtilities().filter((u) => (kind ? u.kind === kind : true));

  if (utilities.length === 0) {
    const noun = kind === "constant" ? "constants" : "utilities";
    return (
      <p>
        <em>No {noun} in the generated dataset.</em>
      </p>
    );
  }

  const showKind = !kind;

  return (
    <div className="mdk-utilities-doc">
      <p>
        Imported from <code>{IMPORT_PACKAGE}</code>.
      </p>
      {groupByCategory(utilities).map(([category, items]) => (
        <div key={category}>
          <h3>{titleCase(category)}</h3>
          <table>
            <thead>
              <tr>
                <th>Name</th>
                {showKind && <th>Kind</th>}
                <th>Signature / Type</th>
                <th>Description</th>
              </tr>
            </thead>
            <tbody>
              {items.map((u) => (
                <tr key={u.name}>
                  <td>
                    <code>{u.name}</code>
                  </td>
                  {showKind && <td>{u.kind}</td>}
                  <td>
                    <code>{u.signature}</code>
                  </td>
                  <td>{u.description || "—"}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ))}
    </div>
  );
}

export default UtilitiesDoc;
