const { execFileSync } = require('child_process')
const path = require('path')
const fs = require('fs')
const initialize = require('./utils/initialize')
const { buildComposeYaml } = require('./utils/compose-yaml')
const { ensureConfigFromExamples, findRepoRoot } = require('./utils/service-bootstrap')

const startServices = async (config) => {
  if (config.runtime === 'pm2') {
    return startPm2(config)
  }

  if (config.runtime === 'docker') {
    return startDocker(config)
  }

  throw new Error(`Unsupported runtime: ${config.runtime}`)
}

function ensureMdkWorker (cwd = process.cwd()) {
  const mdkDir = path.join(cwd, 'mdk')
  const utilsDir = path.join(mdkDir, 'utils')
  fs.mkdirSync(utilsDir, { recursive: true })

  fs.copyFileSync(path.join(__dirname, 'worker.js'), path.join(mdkDir, 'worker.js'))
  fs.copyFileSync(
    path.join(__dirname, 'utils', 'service-bootstrap.js'),
    path.join(utilsDir, 'service-bootstrap.js')
  )

  for (const legacy of [
    path.join(mdkDir, 'pm2-bootstrap.js'),
    path.join(utilsDir, 'pm2-bootstrap.js')
  ]) {
    if (fs.existsSync(legacy)) fs.unlinkSync(legacy)
  }

  return path.join(mdkDir, 'worker.js')
}

function startPm2 (config) {
  const mdkEnv = config.env || 'development'
  const repoRoot = findRepoRoot(process.cwd())

  initialize()
  ensureMdkWorker()
  ensureConfigFromExamples(path.join(repoRoot, 'backend', 'core', 'gateway', 'config'))

  const workerScript = 'mdk/worker.js'
  const sharedEnv = {
    MDK_ENV: mdkEnv,
    NODE_ENV: mdkEnv === 'production' ? 'production' : 'development'
  }

  const apps = config.services.map(svc => {
    if (svc.kind === 'gateway') {
      return {
        name: `mdk-${svc.name}`,
        script: workerScript,
        cwd: process.cwd(),
        exec_mode: 'fork',
        instances: 1,
        env: {
          ...sharedEnv,
          SERVICE: 'gateway',
          PORT: String(svc.port)
        }
      }
    }

    return {
      name: `mdk-${svc.name}`,
      script: workerScript,
      cwd: process.cwd(),
      exec_mode: 'fork',
      instances: 1,
      env: {
        ...sharedEnv,
        SERVICE: 'worker',
        WORKER: svc.worker,
        TYPE: svc.type,
        RACK: svc.rack
      }
    }
  })

  // PM2 only treats filenames containing .config.js (or .json/.yaml) as ecosystem files.
  const file = path.join(process.cwd(), 'ecosystem.config.js')
  const content = `// Auto-generated by @tetherto/mdk — do not edit manually
module.exports = ${JSON.stringify({ apps }, null, 2)}
`

  fs.writeFileSync(file, content)
  if (config.shouldAutoStart) {
    execFileSync('pm2', ['start', file], { stdio: 'inherit' })
  }
}

function startDocker (config) {
  if (!config.image) {
    throw new Error('Docker runtime requires "image"')
  }

  const mdkEnv = config.env || 'development'
  const siteDir = process.cwd()
  const repoRoot = findRepoRoot(siteDir)
  const repoMount = path.relative(siteDir, repoRoot).split(path.sep).join('/') || '.'

  initialize()
  ensureMdkWorker(siteDir)
  ensureConfigFromExamples(path.join(repoRoot, 'backend', 'core', 'gateway', 'config'))

  const siteMount = path.relative(repoRoot, siteDir).split(path.sep).join('/') || '.'
  const workingDir = `/app/repo/${siteMount}`
  const entrypoint = path.posix.join('/app/repo', siteMount, 'docker-entrypoint.sh')

  const sharedEnv = {
    MDK_ENV: mdkEnv,
    NODE_ENV: mdkEnv === 'production' ? 'production' : 'development'
  }

  const services = {}

  for (const svc of config.services) {
    const base = {
      image: config.image,
      working_dir: workingDir,
      entrypoint: ['sh', entrypoint],
      restart: 'unless-stopped',
      volumes: [`${repoMount}:/app/repo:cached`],
      environment: { ...sharedEnv }
    }

    if (svc.kind === 'gateway') {
      services[svc.name] = {
        ...base,
        environment: {
          ...base.environment,
          SERVICE: 'gateway',
          PORT: String(svc.port)
        },
        ports: [`${svc.port}:${svc.port}`]
      }
      continue
    }

    services[svc.name] = {
      ...base,
      environment: {
        ...base.environment,
        SERVICE: 'worker',
        WORKER: svc.worker,
        TYPE: svc.type,
        RACK: svc.rack
      }
    }
  }

  const compose = {
    version: '3.8',
    services
  }

  const file = path.join(siteDir, 'docker-compose.generated.yml')
  fs.writeFileSync(file, buildComposeYaml(compose))

  if (config.shouldAutoStart) {
    execFileSync('docker', ['compose', '-f', file, 'up', '-d'], { stdio: 'inherit', cwd: siteDir })
  }

  return { file, repoRoot, siteDir }
}

module.exports = { startServices }
