import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

import { makeConsumerFixture, noop } from '../test-utils.js'
import { runAddFeature } from './add-feature.js'

describe('runAddFeature', () => {
  let fixture: ReturnType<typeof makeConsumerFixture>
  beforeEach(() => {
    fixture = makeConsumerFixture()
  })
  afterEach(() => fixture.dispose())

  it('happy path: writes a .tsx file from a real blueprint', () => {
    const { writtenPath } = runAddFeature({
      packageName: '@tetherto/mdk-react-devkit',
      blueprintId: 'alerts',
      cwd: fixture.dir,
      outDir: 'src/pages',
      out: noop,
    })

    expect(existsSync(writtenPath)).toBe(true)
    const contents = readFileSync(writtenPath, 'utf8')
    // Should contain generator marker
    expect(contents).toMatch(/generated by `mdk-ui add feature/)
    // Should have renamed default export ending in Page
    expect(contents).toMatch(/export default function \w+Page\(/)
  })

  it('refuses to overwrite when the file already exists without force', () => {
    runAddFeature({
      packageName: '@tetherto/mdk-react-devkit',
      blueprintId: 'alerts',
      cwd: fixture.dir,
      outDir: 'src/pages',
      out: noop,
    })

    expect(() =>
      runAddFeature({
        packageName: '@tetherto/mdk-react-devkit',
        blueprintId: 'alerts',
        cwd: fixture.dir,
        outDir: 'src/pages',
        out: noop,
      }),
    ).toThrow(/already exists/)
  })

  it('overwrites when force: true', () => {
    runAddFeature({
      packageName: '@tetherto/mdk-react-devkit',
      blueprintId: 'alerts',
      cwd: fixture.dir,
      outDir: 'src/pages',
      out: noop,
    })

    expect(() =>
      runAddFeature({
        packageName: '@tetherto/mdk-react-devkit',
        blueprintId: 'alerts',
        cwd: fixture.dir,
        outDir: 'src/pages',
        force: true,
        out: noop,
      }),
    ).not.toThrow()
  })

  it('throws a clear message when the blueprint id does not exist', () => {
    expect(() =>
      runAddFeature({
        packageName: '@tetherto/mdk-react-devkit',
        blueprintId: 'definitely-not-a-blueprint',
        cwd: fixture.dir,
        outDir: 'src/pages',
        out: noop,
      }),
    ).toThrow(/not found/)
  })

  it('throws when no blueprints manifest is published', () => {
    expect(() =>
      runAddFeature({
        packageName: '@tetherto/mdk-react-devkit',
        blueprintId: 'alerts',
        cwd: '/tmp',
        outDir: 'src/pages',
        out: noop,
      }),
    ).toThrow()
  })

  it('uses console.log as the default `out` sink', () => {
    const spy = vi.spyOn(console, 'log').mockImplementation(() => {})
    try {
      runAddFeature({
        packageName: '@tetherto/mdk-react-devkit',
        blueprintId: 'alerts',
        cwd: fixture.dir,
        outDir: 'src/pages',
      })
      expect(spy).toHaveBeenCalled()
    } finally {
      spy.mockRestore()
    }
  })

  it('throws when a blueprint has no ```tsx block', () => {
    // Manually patch blueprints.json in the symlinked devkit copy temporarily
    // by pointing to a fake package dir — easiest approach is to inject
    // a modified version via a custom package dir layout in the fixture.
    // Instead, we verify the error path by using a spy: write a fake
    // blueprints.json into the fixture's node_modules.
    const fakeBlueprintsPath = join(
      fixture.dir,
      'node_modules',
      '@tetherto',
      'mdk-react-devkit',
      'dist',
      'blueprints.json',
    )

    // Read the real one, patch one blueprint body to remove the tsx block
    const real = JSON.parse(readFileSync(fakeBlueprintsPath, 'utf8')) as {
      blueprints: Array<{ id: string; body: string }>
      indexes?: { byId: Record<string, number> }
    }
    const modified = {
      ...real,
      blueprints: real.blueprints.map((b) =>
        b.id === 'alerts' ? { ...b, body: 'No tsx block here.' } : b,
      ),
    }

    writeFileSync(fakeBlueprintsPath, JSON.stringify(modified), 'utf8')

    expect(() =>
      runAddFeature({
        packageName: '@tetherto/mdk-react-devkit',
        blueprintId: 'alerts',
        cwd: fixture.dir,
        outDir: 'src/pages',
        out: noop,
      }),
    ).toThrow(/no `{3}tsx block/)

    // Restore to avoid tainting the symlinked devkit
    writeFileSync(fakeBlueprintsPath, JSON.stringify(real), 'utf8')
  })
})
