import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

import { DIST_DIR, MANIFESTS, NODE_MODULES_DIR, PACKAGE_JSON, PACKAGES } from '../constants.js'
import { DEVKIT_DIR, makeConsumerFixture, noop } from '../test-utils.js'
import { runAddFeature } from './add-feature.js'

describe('runAddFeature', () => {
  let fixture: ReturnType<typeof makeConsumerFixture>
  beforeEach(() => {
    fixture = makeConsumerFixture()
  })
  afterEach(() => fixture.dispose())

  it('happy path: writes a .tsx file from a real blueprint', () => {
    const { writtenPath } = runAddFeature({
      packageName: PACKAGES.devkit,
      blueprintId: 'alerts',
      cwd: fixture.dir,
      outDir: 'src/pages',
      out: noop,
    })

    expect(existsSync(writtenPath)).toBe(true)
    const contents = readFileSync(writtenPath, 'utf8')
    // Should contain generator marker
    expect(contents).toMatch(/generated by `mdk-ui add feature/)
    // Should have renamed default export ending in Page
    expect(contents).toMatch(/export default function \w+Page\(/)
  })

  it('refuses to overwrite when the file already exists without force', () => {
    runAddFeature({
      packageName: PACKAGES.devkit,
      blueprintId: 'alerts',
      cwd: fixture.dir,
      outDir: 'src/pages',
      out: noop,
    })

    expect(() =>
      runAddFeature({
        packageName: PACKAGES.devkit,
        blueprintId: 'alerts',
        cwd: fixture.dir,
        outDir: 'src/pages',
        out: noop,
      }),
    ).toThrow(/already exists/)
  })

  it('overwrites when force: true', () => {
    runAddFeature({
      packageName: PACKAGES.devkit,
      blueprintId: 'alerts',
      cwd: fixture.dir,
      outDir: 'src/pages',
      out: noop,
    })

    expect(() =>
      runAddFeature({
        packageName: PACKAGES.devkit,
        blueprintId: 'alerts',
        cwd: fixture.dir,
        outDir: 'src/pages',
        force: true,
        out: noop,
      }),
    ).not.toThrow()
  })

  it('throws a clear message when the blueprint id does not exist', () => {
    expect(() =>
      runAddFeature({
        packageName: PACKAGES.devkit,
        blueprintId: 'definitely-not-a-blueprint',
        cwd: fixture.dir,
        outDir: 'src/pages',
        out: noop,
      }),
    ).toThrow(/not found/)
  })

  it('throws when no blueprints manifest is published', () => {
    expect(() =>
      runAddFeature({
        packageName: PACKAGES.devkit,
        blueprintId: 'alerts',
        cwd: '/tmp',
        outDir: 'src/pages',
        out: noop,
      }),
    ).toThrow()
  })

  it('uses console.log as the default `out` sink', () => {
    const spy = vi.spyOn(console, 'log').mockImplementation(() => {})
    try {
      runAddFeature({
        packageName: PACKAGES.devkit,
        blueprintId: 'alerts',
        cwd: fixture.dir,
        outDir: 'src/pages',
      })
      expect(spy).toHaveBeenCalled()
    } finally {
      spy.mockRestore()
    }
  })

  it('throws when a blueprint has no ```tsx block', () => {
    // Replace the symlinked devkit with a real copy first, so patching
    // blueprints.json stays local to this fixture and never taints the shared
    // workspace `dist/` (which would race with blueprints.test.ts under
    // vitest's parallel file execution).
    const pkgDir = join(fixture.dir, NODE_MODULES_DIR, PACKAGES.devkit)
    rmSync(pkgDir, { force: true }) // drop the symlink
    mkdirSync(join(pkgDir, DIST_DIR), { recursive: true })
    cpSync(join(DEVKIT_DIR, PACKAGE_JSON), join(pkgDir, PACKAGE_JSON))
    cpSync(join(DEVKIT_DIR, DIST_DIR, MANIFESTS.registry), join(pkgDir, DIST_DIR, MANIFESTS.registry))
    const blueprintsPath = join(pkgDir, DIST_DIR, MANIFESTS.blueprints)
    cpSync(join(DEVKIT_DIR, DIST_DIR, MANIFESTS.blueprints), blueprintsPath)

    // Patch one blueprint body to remove the tsx block.
    const real = JSON.parse(readFileSync(blueprintsPath, 'utf8')) as {
      blueprints: Array<{ id: string; body: string }>
      indexes?: { byId: Record<string, number> }
    }
    const modified = {
      ...real,
      blueprints: real.blueprints.map((b) =>
        b.id === 'alerts' ? { ...b, body: 'No tsx block here.' } : b,
      ),
    }
    writeFileSync(blueprintsPath, JSON.stringify(modified), 'utf8')

    expect(() =>
      runAddFeature({
        packageName: PACKAGES.devkit,
        blueprintId: 'alerts',
        cwd: fixture.dir,
        outDir: 'src/pages',
        out: noop,
      }),
    ).toThrow(/no `{3}tsx block/)
  })
})
