import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

import { makeConsumerFixture, noop } from '../test-utils.js'
import { runAddPage } from './add-page.js'

describe('runAddPage', () => {
  let fixture: ReturnType<typeof makeConsumerFixture>
  beforeEach(() => {
    fixture = makeConsumerFixture()
  })
  afterEach(() => fixture.dispose())

  it('writes a page file that imports the requested component', () => {
    const { writtenPath } = runAddPage({
      packageName: '@tetherto/mdk-react-devkit',
      pageName: 'MyDashboard',
      componentName: 'LineChartCard',
      outDir: 'src/pages',
      cwd: fixture.dir,
      // Use shell mode so the output is always the generated scaffold (not the
      // co-located example, which uses a named export and therefore lacks
      // `export default function`).
      shell: true,
      out: noop,
    })
    expect(writtenPath).toBe(join(fixture.dir, 'src/pages/MyDashboard.tsx'))
    expect(existsSync(writtenPath)).toBe(true)
    const contents = readFileSync(writtenPath, 'utf8')
    expect(contents).toMatch(/import \{ LineChartCard \} from ['"]@tetherto\/mdk-react-devkit['"]/)
    expect(contents).toMatch(/export default function MyDashboardPage/)
    expect(contents).toMatch(/<LineChartCard/)
  })

  it('converts dashed names to PascalCase', () => {
    const { writtenPath } = runAddPage({
      packageName: '@tetherto/mdk-react-devkit',
      pageName: 'fleet-health',
      componentName: 'ActiveIncidentsCard',
      outDir: 'src/pages',
      cwd: fixture.dir,
      out: noop,
    })
    expect(writtenPath).toBe(join(fixture.dir, 'src/pages/FleetHealth.tsx'))
    const contents = readFileSync(writtenPath, 'utf8')
    expect(contents).toMatch(/FleetHealthPage/)
    expect(contents).toMatch(/<ActiveIncidentsCard/)
  })

  it('refuses to overwrite without --force', () => {
    runAddPage({
      packageName: '@tetherto/mdk-react-devkit',
      pageName: 'Dup',
      componentName: 'LineChartCard',
      outDir: 'src/pages',
      cwd: fixture.dir,
      out: noop,
    })
    expect(() =>
      runAddPage({
        packageName: '@tetherto/mdk-react-devkit',
        pageName: 'Dup',
        componentName: 'LineChartCard',
        outDir: 'src/pages',
        cwd: fixture.dir,
        out: noop,
      }),
    ).toThrow(/already exists/)
  })

  it('overwrites when --force is set', () => {
    runAddPage({
      packageName: '@tetherto/mdk-react-devkit',
      pageName: 'Forced',
      componentName: 'LineChartCard',
      outDir: 'src/pages',
      cwd: fixture.dir,
      out: noop,
    })
    expect(() =>
      runAddPage({
        packageName: '@tetherto/mdk-react-devkit',
        pageName: 'Forced',
        componentName: 'ActiveIncidentsCard',
        outDir: 'src/pages',
        cwd: fixture.dir,
        force: true,
        out: noop,
      }),
    ).not.toThrow()
    const contents = readFileSync(join(fixture.dir, 'src/pages/Forced.tsx'), 'utf8')
    expect(contents).toMatch(/<ActiveIncidentsCard/)
  })

  it('throws for unknown components', () => {
    expect(() =>
      runAddPage({
        packageName: '@tetherto/mdk-react-devkit',
        pageName: 'Bad',
        componentName: 'DefinitelyNotAComponent',
        outDir: 'src/pages',
        cwd: fixture.dir,
        out: noop,
      }),
    ).toThrow(/not found/)
  })

  it('resolves component from pageName via substring match when componentName is omitted', () => {
    // "chartcard" is a unique substring in "LineChartCard"
    const { writtenPath } = runAddPage({
      packageName: '@tetherto/mdk-react-devkit',
      pageName: 'ChartCard',
      outDir: 'src/pages',
      cwd: fixture.dir,
      shell: true,
      out: noop,
    })
    expect(existsSync(writtenPath)).toBe(true)
    const contents = readFileSync(writtenPath, 'utf8')
    expect(contents).toMatch(/LineChartCard/)
  })

  it('writes content from a co-located example when shell: false', () => {
    // When shell is not set (defaults to false), the example-based path is used
    const { writtenPath } = runAddPage({
      packageName: '@tetherto/mdk-react-devkit',
      pageName: 'ChartDashboard',
      componentName: 'LineChartCard',
      outDir: 'src/pages',
      cwd: fixture.dir,
      out: noop,
    })
    expect(existsSync(writtenPath)).toBe(true)
    const contents = readFileSync(writtenPath, 'utf8')
    // The example-based path always includes the generator marker in the header
    expect(contents).toMatch(/generated by `mdk-ui add page`/)
    expect(contents).toMatch(/LineChartCard/)
    // Must have a default export so React.lazy() can resolve it
    expect(contents).toMatch(/export default/)
  })

  it('generates a default export when the example uses a named arrow function export', () => {
    // Alerts.example.tsx uses `export const AlertsExample = () => {` — no default export.
    // adaptExampleToPage must add one so React.lazy() doesn't blow up.
    const { writtenPath } = runAddPage({
      packageName: '@tetherto/mdk-react-devkit',
      pageName: 'AlertsPage',
      componentName: 'Alerts',
      outDir: 'src/pages',
      cwd: fixture.dir,
      out: noop,
    })
    const contents = readFileSync(writtenPath, 'utf8')
    expect(contents).toMatch(/export default/)
    // The original named export should no longer be the only export
    expect(contents).not.toMatch(/^export const AlertsExample/m)
  })

  it('resolveComponent throws when pageName is ambiguous (multiple substring matches)', () => {
    // "chart" matches many components like LineChart, LineChartCard, AreaChart...
    expect(() =>
      runAddPage({
        packageName: '@tetherto/mdk-react-devkit',
        pageName: 'chart',
        outDir: 'src/pages',
        cwd: fixture.dir,
        shell: true,
        out: noop,
      }),
    ).toThrow(/ambiguous|multiple|Re-run/)
  })

  it('throws when no component matches the pageName at all', () => {
    expect(() =>
      runAddPage({
        packageName: '@tetherto/mdk-react-devkit',
        pageName: 'zzz-completely-unmatchable-string',
        outDir: 'src/pages',
        cwd: fixture.dir,
        shell: true,
        out: noop,
      }),
    ).toThrow(/No component matches/)
  })

  it('uses console.log as the default `out` sink', () => {
    const spy = vi.spyOn(console, 'log').mockImplementation(() => {})
    try {
      runAddPage({
        packageName: '@tetherto/mdk-react-devkit',
        pageName: 'ConsolePage',
        componentName: 'LineChartCard',
        outDir: 'src/pages',
        cwd: fixture.dir,
        shell: true,
      })
      expect(spy).toHaveBeenCalled()
    } finally {
      spy.mockRestore()
    }
  })

  it('does not re-register a route that is already present', () => {
    mkdirSync(join(fixture.dir, 'src'), { recursive: true })
    writeFileSync(
      join(fixture.dir, 'src', 'routes.tsx'),
      `export const ROUTES = [\n  { path: '/dupe', label: 'Dupe', page: () => import('./pages/Dupe') },\n  // mdk:routes-end\n];\n`,
      'utf8',
    )

    const lines: string[] = []
    runAddPage({
      packageName: '@tetherto/mdk-react-devkit',
      pageName: 'Dupe',
      componentName: 'LineChartCard',
      outDir: 'src/pages',
      cwd: fixture.dir,
      shell: true,
      out: (l) => lines.push(l),
    })

    expect(lines.every((l) => !l.includes('Registered route'))).toBe(true)
  })

  it('patches a routes file when one exists with the routes-end marker', () => {
    mkdirSync(join(fixture.dir, 'src'), { recursive: true })
    writeFileSync(
      join(fixture.dir, 'src', 'routes.ts'),
      `export const ROUTES = [\n  // mdk:routes-end\n];\n`,
      'utf8',
    )

    const lines: string[] = []
    runAddPage({
      packageName: '@tetherto/mdk-react-devkit',
      pageName: 'RouteTest',
      componentName: 'LineChartCard',
      outDir: 'src/pages',
      cwd: fixture.dir,
      shell: true,
      out: (l) => lines.push(l),
    })

    const routeContent = readFileSync(join(fixture.dir, 'src', 'routes.ts'), 'utf8')
    expect(routeContent).toMatch(/routetest/)
    expect(lines.some((l) => l.includes('Registered route'))).toBe(true)
  })
})
