import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

import { findBlueprint, loadBlueprints } from '../registry-loader.js'
import { toPascalCase } from '../utils.js'
import { patchRoutesFile } from './add-page.js'

export type AddFeatureOptions = {
  packageName: string
  blueprintId: string
  cwd: string
  outDir: string
  routePath?: string
  pageName?: string
  force?: boolean
  out?: (line: string) => void
}

const toKebabCase = (input: string): string =>
  input
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase()

/**
 * Extract the first ```tsx ... ``` fenced code block from a markdown string.
 */
const extractTsxBlock = (body: string): string | null => {
  const match = /```tsx\r?\n([\s\S]*?)```/.exec(body)
  return match?.[1]?.trimEnd() ?? null
}

/**
 * Rename the `export default function <Whatever>` in a TSX snippet to
 * `export default function <PageName>`.
 */
const renameDefaultExport = (source: string, pageName: string): string =>
  source.replace(/export default function\s+\w+\s*\(/, `export default function ${pageName}(`)

export const runAddFeature = (opts: AddFeatureOptions): { writtenPath: string } => {
  const out =
    opts.out ??
    ((line: string) => {
      // eslint-disable-next-line no-console
      console.log(line)
    })

  const manifest = loadBlueprints({ packageName: opts.packageName, cwd: opts.cwd })
  if (!manifest) {
    throw new Error(
      `No blueprints found for ${opts.packageName}. Run \`npm run build --workspace ${opts.packageName}\` first.`,
    )
  }

  const blueprint = findBlueprint(manifest, opts.blueprintId)
  if (!blueprint) {
    const ids = manifest.blueprints.map((entry) => entry.id).join(', ')
    throw new Error(`Blueprint "${opts.blueprintId}" not found. Available: ${ids}`)
  }

  const tsxBlock = extractTsxBlock(blueprint.body)
  if (!tsxBlock) {
    throw new Error(
      `Blueprint "${opts.blueprintId}" has no \`\`\`tsx block under ## Page composition. ` +
        `Add one to the blueprint markdown.`,
    )
  }

  const pagePascal = toPascalCase(opts.pageName ?? opts.blueprintId)
  const pageName = pagePascal.endsWith('Page') ? pagePascal : `${pagePascal}Page`

  const routePath =
    opts.routePath ??
    (blueprint.demoRoute ? blueprint.demoRoute : `/${toKebabCase(opts.blueprintId)}`)

  const source = renameDefaultExport(tsxBlock, pageName)
  const hooksLine = blueprint.hooks.length ? `\n * Hooks: ${blueprint.hooks.join(', ')}` : ''
  const contents = `\
/**
 * ${pageName} — generated by \`mdk-ui add feature ${opts.blueprintId}\`.
 *
 * Blueprint: ${blueprint.title}
 * Components: ${blueprint.components.join(', ')}${hooksLine}
 *
 * Edit freely — the generator marker above lets \`mdk-ui remove page\` clean
 * this file up safely.
 */
${source}
`

  const fileName = `${pageName}.tsx`
  const targetDir = resolve(opts.cwd, opts.outDir)
  const targetPath = join(targetDir, fileName)

  if (existsSync(targetPath) && !opts.force) {
    throw new Error(`${targetPath} already exists. Re-run with --force to overwrite.`)
  }

  mkdirSync(targetDir, { recursive: true })
  writeFileSync(targetPath, contents, 'utf8')
  out(`✓ Wrote ${targetPath} (from blueprint "${opts.blueprintId}")`)

  patchRoutesFile(opts.cwd, pageName, routePath, out)

  out('')
  out(`This feature uses:`)
  out(`  Components: ${blueprint.components.join(', ')}`)
  if (blueprint.hooks.length) out(`  Hooks: ${blueprint.hooks.join(', ')}`)
  out(`Make sure <MdkProvider> wraps your app root (the starter template already does this).`)

  return { writtenPath: targetPath }
}
