import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

import { readExampleSource } from '../examples.js'
import { findManagedPage, type ManagedPage } from '../managed-pages.js'
import { patchNavIcon } from '../nav.js'
import {
  findComponent,
  loadRegistry,
  type Registry,
  type RegistryComponent,
} from '../registry-loader.js'
import { findRoutesFile, ROUTES_END_MARKER } from '../routes-file.js'
import { getTemplatesRoot } from '../templates.js'
import { placeholderFor, toPascalCase } from '../utils.js'

// Re-exported for the legacy `import { ROUTES_CANDIDATES } from './add-page.js'`
// callsite; new code should import from `../routes-file.js`.
export { ROUTES_CANDIDATES } from '../routes-file.js'

export type AddPageOptions = {
  packageName: string
  pageName: string
  /** Explicit component name. When omitted, resolved from pageName via fuzzy match. */
  componentName?: string
  outDir: string
  cwd: string
  force?: boolean
  /** Skip the example file even when one is available; emit the placeholder shell. */
  shell?: boolean
  out?: (line: string) => void
}

const generateShell = (
  pageName: string,
  component: RegistryComponent,
  packageName: string,
): string => {
  const requiredProps = component.props.filter((p) => p.required)
  const propLines = requiredProps.map((p) => `      ${p.name}=${placeholderFor(p.type)}`).join('\n')

  return `\
/**
 * ${pageName}Page — generated by \`mdk-ui add page\`.
 *
 * Renders the \`${component.name}\` component from \`${packageName}\`. Adapt the
 * required props below or wire them to a TanStack Query hook backed by your
 * own API.
 */
import { ${component.name} } from "${packageName}";

export default function ${pageName}Page() {
  return (
    <${component.name}
${propLines}
    />
  );
}
`
}

/**
 * Wrap a runnable example file as a page module:
 *  - prepend a generator marker comment so `remove page` recognises it,
 *  - rename the default-exported function to `<PageName>Page` so the page
 *    has a stable identity regardless of the example's local name.
 */
const adaptExampleToPage = (
  source: string,
  pageName: string,
  component: RegistryComponent,
  examplePath: string,
): string => {
  const header = `\
/**
 * ${pageName}Page — generated by \`mdk-ui add page\` from the example for
 * \`${component.name}\` (source: ${examplePath}). Adapt freely.
 */
`
  // Case 1: example already uses `export default function Name(`
  if (/export default function\s+\w+\s*\(/.test(source)) {
    const renamed = source.replace(
      /export default function\s+(\w+)\s*\(/,
      `export default function ${pageName}Page(`,
    )
    return header + renamed
  }

  // Case 2: example uses `export const Name = ...` (arrow function / FC)
  // Rename the const and append a default export so lazy() gets a default.
  const arrowMatch = source.match(/export const (\w+) *(:[^=]+)?=/)
  if (arrowMatch?.[1]) {
    const originalName = arrowMatch[1]
    const renamed = source
      .replace(/export const \w+/, `const ${pageName}Page`)
      .replace(new RegExp(`\\b${originalName}\\b`, 'g'), `${pageName}Page`)
    return `${header}${renamed}\nexport default ${pageName}Page\n`
  }

  // Fallback: append a default re-export of whatever is exported
  return `${header}${source}\nexport default ${pageName}Page\n`
}

/**
 * Resolve a registry component from a free-form page name when the user
 * omitted `--component`. The rules are deliberately strict so failures are
 * deterministic and actionable for agents.
 */
export const resolveComponent = (
  registry: Registry,
  pageName: string,
): { component: RegistryComponent; reason: string } => {
  const needle = pageName.toLowerCase()
  const exact = registry.components.filter((c) => c.name.toLowerCase() === needle)
  if (exact.length === 1 && exact[0]) {
    return { component: exact[0], reason: 'exact match' }
  }
  if (exact.length > 1) {
    const list = exact.map((c) => c.name).join(', ')
    throw new Error(
      `"${pageName}" matches multiple components exactly: ${list}. Re-run with --component <Name>.`,
    )
  }
  const substring = registry.components.filter((c) => c.name.toLowerCase().includes(needle))
  if (substring.length === 1 && substring[0]) {
    return { component: substring[0], reason: `substring match (${substring[0].name})` }
  }
  if (substring.length > 1) {
    const top = substring.slice(0, 5).map((c) => c.name)
    throw new Error(
      `"${pageName}" is ambiguous. Candidates:\n  ${top.join('\n  ')}\nRe-run with --component <Name>.`,
    )
  }
  throw new Error(
    `No component matches "${pageName}". Try:\n  npx mdk-ui suggest "${pageName}"\n  npx mdk-ui registry --filter components --format table`,
  )
}

/**
 * Append a new route entry to the project's routes manifest if one exists
 * (identified by a `// mdk:routes-end` marker). Does nothing when the file
 * is absent or the route path is already registered.
 */
export const patchRoutesFile = (
  cwd: string,
  pagePascal: string,
  routePath: string,
  out: (line: string) => void,
): void => {
  const routesFile = findRoutesFile(cwd)
  if (!routesFile) return

  const content = readFileSync(routesFile, 'utf8')
  if (content.includes(`'${routePath}'`) || content.includes(`"${routePath}"`)) return

  const importPath = `./pages/${pagePascal}`
  // Convert PascalCase to "Title Case" and strip a trailing "Page" suffix
  const humanLabel = pagePascal
    .replace(/([A-Z])/g, ' $1')
    .trim()
    .replace(/\s+Page$/, '')
  const newEntry = `  { path: '${routePath}', label: '${humanLabel}', page: () => import('${importPath}') },`
  const patched = content.replace(ROUTES_END_MARKER, `${newEntry}\n$1// mdk:routes-end`)

  writeFileSync(routesFile, patched, 'utf8')
  out(`✓ Registered route ${routePath} in ${routesFile}`)
}

/**
 * Insert a managed page's canonical `ROUTES` entry before the routes marker.
 * No-op when the route is already registered or the routes file/marker is
 * absent. Mirrors {@link patchRoutesFile} but writes the exact pre-seeded line
 * (so e.g. Alerts keeps its `routePath: '/alerts/:uuid?'` deep-link segment).
 */
const patchManagedRoute = (cwd: string, page: ManagedPage, out: (line: string) => void): void => {
  const routesFile = findRoutesFile(cwd)
  if (!routesFile) return

  const content = readFileSync(routesFile, 'utf8')
  if (content.includes(`path: '${page.routePath}'`)) return
  if (!ROUTES_END_MARKER.test(content)) return

  const patched = content.replace(ROUTES_END_MARKER, `$1${page.routeEntry}\n$1// mdk:routes-end`)
  writeFileSync(routesFile, patched, 'utf8')
  out(`✓ Registered route ${page.routePath} in ${routesFile}`)
}

/**
 * Scaffold a pre-seeded managed page (Pool Manager, Alerts): copy the canonical
 * fully-wired page bundled with the CLI verbatim, then register its route and
 * sidebar nav icon. The reverse of `remove page` for the same page.
 */
const addManagedPage = (
  page: ManagedPage,
  opts: AddPageOptions,
  out: (line: string) => void,
): { writtenPath: string } => {
  const sourcePath = join(getTemplatesRoot(), page.templateId, page.templatePagePath)
  if (!existsSync(sourcePath)) {
    throw new Error(`Managed page template not found: ${sourcePath}`)
  }
  const contents = readFileSync(sourcePath, 'utf8')

  const fileName = `${page.name}.tsx`
  const targetDir = resolve(opts.cwd, opts.outDir)
  const targetPath = join(targetDir, fileName)
  if (existsSync(targetPath) && !opts.force) {
    throw new Error(`${targetPath} already exists. Re-run with --force to overwrite.`)
  }

  mkdirSync(targetDir, { recursive: true })
  writeFileSync(targetPath, contents, 'utf8')
  out(`✓ Wrote ${targetPath} (managed page: ${page.name})`)

  patchManagedRoute(opts.cwd, page, out)
  patchNavIcon(opts.cwd, page, out)

  return { writtenPath: targetPath }
}

export const runAddPage = (opts: AddPageOptions): { writtenPath: string } => {
  const out =
    opts.out ??
    ((s: string) => {
      // eslint-disable-next-line no-console
      console.log(s)
    })

  // Pre-seeded, fully-wired pages resolve to a canonical bundled page rather
  // than a registry example. An explicit --component or --shell opts back out
  // to the generic scaffold path.
  if (!opts.componentName && !opts.shell) {
    const managed = findManagedPage(opts.pageName)
    if (managed) return addManagedPage(managed, opts, out)
  }

  const { registry, packageDir } = loadRegistry({
    packageName: opts.packageName,
    cwd: opts.cwd,
  })

  let component: RegistryComponent | undefined
  if (opts.componentName) {
    component = findComponent(registry, opts.componentName)
    if (!component) {
      throw new Error(`Component "${opts.componentName}" not found in registry.`)
    }
  } else {
    const resolved = resolveComponent(registry, opts.pageName)
    component = resolved.component
    out(`→ Resolved "${opts.pageName}" → ${component.name} (${resolved.reason})`)
  }

  const pagePascal = toPascalCase(opts.pageName)
  const example = opts.shell ? null : readExampleSource(packageDir, component)
  const contents = example
    ? adaptExampleToPage(example.source, pagePascal, component, example.path)
    : generateShell(pagePascal, component, opts.packageName)

  const fileName = `${pagePascal}.tsx`
  const targetDir = resolve(opts.cwd, opts.outDir)
  const targetPath = join(targetDir, fileName)

  if (existsSync(targetPath) && !opts.force) {
    throw new Error(`${targetPath} already exists. Re-run with --force to overwrite.`)
  }

  mkdirSync(targetDir, { recursive: true })
  writeFileSync(targetPath, contents, 'utf8')
  out(`✓ Wrote ${targetPath}${example ? ` (from example ${example.path})` : ''}`)

  const routePath = `/${pagePascal.replace(/Page$/, '').toLowerCase()}`
  patchRoutesFile(opts.cwd, pagePascal, routePath, out)

  return { writtenPath: targetPath }
}
