import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { loadRegistry } from '../registry-loader.js'
import { runSync } from './sync.js'

export type InitOptions = {
  packageName: string
  ide: 'cursor' | 'claude' | 'none'
  cwd: string
  force?: boolean
  out?: (line: string) => void
}

const buildContextMarkdown = (
  packageName: string,
  componentCount: number,
  hookCount: number,
): string => `# MDK context

> Generated by \`mdk-ui init\`. Re-run \`mdk-ui sync\` to refresh the Existing
> pages / hooks sections.

This project consumes \`${packageName}\` for its UI layer. AI agents should
**prefer MDK components over hand-rolled HTML** wherever a component exists.

## Navigating by intent (start here)

For any free-form goal — "build a mining dashboard", "add a reporting view",
"add weather widget" — follow this deterministic flow before touching files:

\`\`\`bash
# 1. Find candidate components/blueprints from the user's words.
npx mdk-ui suggest "<user intent>"

# 2. See if a curated recipe already exists for this goal.
npx mdk-ui blueprints                       # list all
npx mdk-ui blueprint <id>                   # print one (markdown body)

# 3. If no blueprint matches, narrow by facet:
npx mdk-ui find --domain mining-operations --capability hashrate-monitoring
\`\`\`

Blueprints cover: \`mining-operations-dashboard\`, \`reporting\`,
\`device-management\`, and \`custom-feature\` (the latter is the answer for
domains MDK doesn't ship — weather, inventory, etc.).

## Reading a component contract

\`\`\`bash
npx mdk-ui registry --filter components --format table   # browse the curated agent-ready surface
npx mdk-ui docs <ComponentName>                          # co-located USAGE.md
npx mdk-ui example <ComponentName>                       # runnable *.example.tsx
\`\`\`

The full registry (${componentCount} components, ${hookCount} hooks) is also
available as a JSON manifest with O(1) indexes:

\`\`\`bash
node -e 'const r=require("${packageName}/registry.json"); console.log(r.indexes.componentsByKernelCapability)'
\`\`\`

## Reading the state and data-fetching surface

\`\`\`bash
# React hooks provided by the adapter (store / utility / permission / ui / external)
npx mdk-ui hooks                                 # full manifest
npx mdk-ui hooks --category store --format table # just the store-binding hooks

# Zustand stores + TanStack Query helpers from ui-foundation
npx mdk-ui stores                                # full manifest
npx mdk-ui stores --category devices --format table
\`\`\`

## Scaffolding new pages

\`\`\`bash
npx mdk-ui add page MyPage --component LineChartCard
npx mdk-ui check src/pages/MyPage.tsx   # structured JSON; self-correct if errors
\`\`\`

This writes \`src/pages/MyPage.tsx\` with the correct imports and required
prop placeholders. Replace the placeholders with real data (TanStack Query is
already configured under \`<MdkProvider>\`).

## Conventions

- Always wrap the app in \`<MdkProvider>\` from \`@tetherto/mdk-react-adapter\`.
- Pull components from \`${packageName}\` first; only hand-roll markup when
  there is no equivalent component in the registry. For genuinely
  out-of-scope domains, follow the \`custom-feature\` blueprint.
- Use the BEM class names (\`mdk-...\`) only for layer-app overrides under
  \`@layer app\`. Do **not** restyle MDK internals.

## Existing pages

<!-- mdk:pages:start -->
_None yet. Run \`mdk-ui sync\` after adding pages._
<!-- mdk:pages:end -->

## Existing hooks

<!-- mdk:hooks:start -->
_None yet. Run \`mdk-ui sync\` after adopting hooks._
<!-- mdk:hooks:end -->
`

const buildGitignore = (existing: string): string => {
  if (/^\.mdk\/context\.md$/m.test(existing)) return existing
  const suffix = existing.endsWith('\n') || existing === '' ? '' : '\n'
  return `${existing}${suffix}\n# MDK agent context (regenerated locally)\n.mdk/context.md\n`
}

const buildCursorRule = (packageName: string): string => `---
description: MDK UI conventions
globs:
  - "**/*"
alwaysApply: true
---

# MDK UI

This project uses [\`${packageName}\`](${packageName}) for the UI layer. When
writing or modifying a UI feature:

1. **Start with intent → recipe.** Run \`npx mdk-ui suggest "<user goal>"\`
   and \`npx mdk-ui blueprints\`. If a blueprint matches, run
   \`npx mdk-ui blueprint <id>\` and follow it.
2. If no blueprint matches, run \`npx mdk-ui find --domain <X> --capability <Y>\`
   to narrow the registry. Fall back to \`npx mdk-ui registry --format table\`.
3. For every component you plan to use, run \`npx mdk-ui docs <ComponentName>\`
   and \`npx mdk-ui example <ComponentName>\` before generating code.
4. For state and data-fetching, check the adapter hooks first:
   \`npx mdk-ui hooks --format table\`. For Zustand stores and query helpers:
   \`npx mdk-ui stores --format table\`.
5. Prefer an MDK component over hand-written HTML or third-party libraries.
   For genuinely out-of-scope domains follow the \`custom-feature\` blueprint —
   do **not** fork mining components.
6. Wrap the root in \`<MdkProvider>\` from \`@tetherto/mdk-react-adapter\`.
7. After adding a page, run \`npx mdk-ui check <file>\` and \`npx mdk-ui sync\`.
`

const buildClaudeMd = (packageName: string): string => `# MDK UI

This project uses [\`${packageName}\`](${packageName}) for the UI layer.

When asked to add or modify a UI feature, use the MDK CLI in this order:

1. \`npx mdk-ui suggest "<user goal>"\` — get a shortlist of components,
   hooks, blueprints, adapter hooks and stores scored by keyword overlap.
2. \`npx mdk-ui blueprints\` / \`npx mdk-ui blueprint <id>\` — load the
   curated recipe for the matched intent.
3. \`npx mdk-ui find --domain <X> --capability <Y>\` — if no blueprint fits,
   filter the registry by facets.
4. \`npx mdk-ui docs <Component>\` + \`npx mdk-ui example <Component>\` for
   every component you'll generate code against.
5. \`npx mdk-ui hooks --format table\` — browse adapter hooks (state,
   utilities, permissions, etc.) before wiring up data or auth.
6. \`npx mdk-ui stores --format table\` — browse Zustand stores and
   TanStack Query helpers before adding data-fetching logic.
7. \`npx mdk-ui add page <Name> --component <Component>\` to scaffold.
8. \`npx mdk-ui check <file>\` after editing to surface type errors.

After making page changes, run \`npx mdk-ui sync\` so \`.mdk/context.md\` keeps
the "Existing pages" / "Existing hooks" sections in sync.

For out-of-scope domains (weather, inventory, etc.) read
\`npx mdk-ui blueprint custom-feature\` — MDK does not ship domain
components there; compose from \`core/\` primitives instead.
`

export const runInit = async (opts: InitOptions): Promise<void> => {
  const out =
    opts.out ??
    ((s: string) => {
      // eslint-disable-next-line no-console
      console.log(s)
    })

  const { registry } = loadRegistry({ packageName: opts.packageName, cwd: opts.cwd })

  const mdkDir = join(opts.cwd, '.mdk')
  mkdirSync(mdkDir, { recursive: true })

  const contextPath = join(mdkDir, 'context.md')
  if (existsSync(contextPath) && !opts.force) {
    out(`• ${contextPath} already exists, skipping (use --force to overwrite).`)
  } else {
    writeFileSync(
      contextPath,
      buildContextMarkdown(opts.packageName, registry.components.length, registry.hooks.length),
      'utf8',
    )
    out(`✓ Wrote ${contextPath}`)
  }

  // .gitignore — ensure `.mdk/context.md` is ignored.
  const gitignorePath = join(opts.cwd, '.gitignore')
  const existing = existsSync(gitignorePath) ? readFileSync(gitignorePath, 'utf8') : ''
  const next = buildGitignore(existing)
  if (next !== existing) {
    writeFileSync(gitignorePath, next, 'utf8')
    out(`✓ Added .mdk/context.md to ${gitignorePath}`)
  }

  // IDE wiring (committed).
  if (opts.ide === 'cursor') {
    const rulesDir = join(opts.cwd, '.cursor', 'rules')
    mkdirSync(rulesDir, { recursive: true })
    const file = join(rulesDir, 'mdk.mdc')
    if (existsSync(file) && !opts.force) {
      out(`• ${file} already exists, skipping.`)
    } else {
      writeFileSync(file, buildCursorRule(opts.packageName), 'utf8')
      out(`✓ Wrote ${file}`)
    }
  } else if (opts.ide === 'claude') {
    const file = join(opts.cwd, 'CLAUDE.md')
    if (existsSync(file) && !opts.force) {
      out(`• ${file} already exists, skipping.`)
    } else {
      writeFileSync(file, buildClaudeMd(opts.packageName), 'utf8')
      out(`✓ Wrote ${file}`)
    }
  }

  // Seed the Existing-pages / Existing-hooks sections.
  await runSync({ cwd: opts.cwd, silent: true })
}
