import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { afterEach, beforeEach, describe, expect, it } from 'vitest'

import { makeConsumerFixture, noop } from '../test-utils.js'
import { runAddPage } from './add-page.js'
import { runRemovePage } from './remove-page.js'

/** Routes manifest with the marker but no managed entries (post-remove state). */
const EMPTY_ROUTES = `import type { ComponentType } from 'react'

export interface AppRoute {
  path: string
  routePath?: string
  label: string
  page: () => Promise<{ default: ComponentType }>
}

export const ROUTES: AppRoute[] = [
  // mdk:routes-end
]
`

/** Nav manifest with the markers but no managed icons (post-remove state). */
const EMPTY_NAV = `import type { ReactNode } from 'react'
import {
  DashboardNavIcon,
  ExplorerNavIcon,
  // mdk:nav-icons-end
} from '@tetherto/mdk-react-devkit'

import { ROUTE_PATHS } from './routes'

const NAV_ICONS: Record<string, ReactNode> = {
  [ROUTE_PATHS.DASHBOARD]: <DashboardNavIcon />,
  // mdk:nav-end
}

const DEFAULT_NAV_ICON: ReactNode = <ExplorerNavIcon />

export const getNavIcon = (path: string): ReactNode => NAV_ICONS[path] ?? DEFAULT_NAV_ICON
`

const seedShell = (dir: string, routes = EMPTY_ROUTES, nav = EMPTY_NAV): void => {
  mkdirSync(join(dir, 'src', 'constants'), { recursive: true })
  writeFileSync(join(dir, 'src', 'routes.ts'), routes, 'utf8')
  writeFileSync(join(dir, 'src', 'constants', 'navigation.tsx'), nav, 'utf8')
}

const readFile = (dir: string, rel: string): string => readFileSync(join(dir, rel), 'utf8')

describe('managed pages (add/remove lifecycle)', () => {
  let fixture: ReturnType<typeof makeConsumerFixture>
  beforeEach(() => {
    fixture = makeConsumerFixture()
  })
  afterEach(() => fixture.dispose())

  it('add page PoolManager copies the wired page and registers route + nav icon', () => {
    seedShell(fixture.dir)

    const { writtenPath } = runAddPage({
      packageName: '@tetherto/mdk-react-devkit',
      pageName: 'PoolManager',
      outDir: 'src/pages',
      cwd: fixture.dir,
      out: noop,
    })

    const page = readFileSync(writtenPath, 'utf8')
    // Canonical wired page — not a placeholder/mock example.
    expect(page).toMatch(/useMinerDevices/)
    expect(page).toMatch(/usePoolManagerDashboard/)
    expect(page).toMatch(/generated by `mdk-ui add page`/)

    const routes = readFile(fixture.dir, 'src/routes.ts')
    expect(routes).toMatch(/path: '\/pool-manager'/)

    const nav = readFile(fixture.dir, 'src/constants/navigation.tsx')
    expect(nav).toMatch(/^\s*PoolManagerNavIcon,\s*$/m)
    expect(nav).toMatch(/<PoolManagerNavIcon \/>/)
  })

  it('add page Alerts copies the wired page and registers route + nav icon', () => {
    seedShell(fixture.dir)

    runAddPage({
      packageName: '@tetherto/mdk-react-devkit',
      pageName: 'Alerts',
      outDir: 'src/pages',
      cwd: fixture.dir,
      out: noop,
    })

    const page = readFile(fixture.dir, 'src/pages/Alerts.tsx')
    expect(page).toMatch(/useCurrentAlertDevices/)

    const routes = readFile(fixture.dir, 'src/routes.ts')
    expect(routes).toMatch(/path: '\/alerts'/)
    // Keeps the deep-link route segment from the canonical entry.
    expect(routes).toMatch(/routePath: '\/alerts\/:uuid\?'/)

    const nav = readFile(fixture.dir, 'src/constants/navigation.tsx')
    expect(nav).toMatch(/^\s*AlertsNavIcon,\s*$/m)
    expect(nav).toMatch(/<AlertsNavIcon \/>/)
  })

  it('add page SiteOverview copies the wired page and registers route + nav icon', () => {
    seedShell(fixture.dir)

    const { writtenPath } = runAddPage({
      packageName: '@tetherto/mdk-react-devkit',
      pageName: 'SiteOverview',
      outDir: 'src/pages',
      cwd: fixture.dir,
      out: noop,
    })

    const page = readFileSync(writtenPath, 'utf8')
    // Canonical wired page — renders the ContainerWidgets feature.
    expect(page).toMatch(/ContainerWidgets/)
    expect(page).toMatch(/generated by `mdk-ui add page`/)

    const routes = readFile(fixture.dir, 'src/routes.ts')
    expect(routes).toMatch(/path: '\/site-overview'/)

    const nav = readFile(fixture.dir, 'src/constants/navigation.tsx')
    expect(nav).toMatch(/^\s*ContainerWidgetsNavIcon,\s*$/m)
    expect(nav).toMatch(/<ContainerWidgetsNavIcon \/>/)
  })

  it('add → remove → add round-trips SiteOverview cleanly', () => {
    seedShell(fixture.dir)
    const opts = {
      packageName: '@tetherto/mdk-react-devkit',
      pageName: 'SiteOverview',
      outDir: 'src/pages',
      cwd: fixture.dir,
      out: noop,
    }

    runAddPage(opts)
    runRemovePage({ pageName: 'SiteOverview', outDir: 'src/pages', cwd: fixture.dir, out: noop })

    expect(existsSync(join(fixture.dir, 'src/pages/SiteOverview.tsx'))).toBe(false)
    expect(readFile(fixture.dir, 'src/constants/navigation.tsx')).not.toMatch(
      /ContainerWidgetsNavIcon/,
    )
    expect(readFile(fixture.dir, 'src/routes.ts')).not.toMatch(/path: '\/site-overview'/)

    runAddPage(opts)
    expect(existsSync(join(fixture.dir, 'src/pages/SiteOverview.tsx'))).toBe(true)
    expect(readFile(fixture.dir, 'src/constants/navigation.tsx')).toMatch(
      /<ContainerWidgetsNavIcon \/>/,
    )
    expect(readFile(fixture.dir, 'src/routes.ts')).toMatch(/path: '\/site-overview'/)
  })

  it('add page Explorer copies the wired page and registers route + nav icon', () => {
    seedShell(fixture.dir)

    const { writtenPath } = runAddPage({
      packageName: '@tetherto/mdk-react-devkit',
      pageName: 'Explorer',
      outDir: 'src/pages',
      cwd: fixture.dir,
      out: noop,
    })

    const page = readFileSync(writtenPath, 'utf8')
    expect(page).toMatch(/ExplorerLayout/)
    expect(page).toMatch(/generated by `mdk-ui add page`/)

    const routes = readFile(fixture.dir, 'src/routes.ts')
    expect(routes).toMatch(/path: '\/explorer'/)

    const nav = readFile(fixture.dir, 'src/constants/navigation.tsx')
    expect(nav).toMatch(/\[ROUTE_PATHS\.EXPLORER\]: <ExplorerNavIcon \/>/)
  })

  it('remove page Explorer drops its nav entry but keeps the ExplorerNavIcon default import', () => {
    seedShell(fixture.dir)
    const opts = {
      packageName: '@tetherto/mdk-react-devkit',
      pageName: 'Explorer',
      outDir: 'src/pages',
      cwd: fixture.dir,
      out: noop,
    }

    runAddPage(opts)
    runRemovePage({ pageName: 'Explorer', outDir: 'src/pages', cwd: fixture.dir, out: noop })

    expect(existsSync(join(fixture.dir, 'src/pages/Explorer.tsx'))).toBe(false)
    expect(readFile(fixture.dir, 'src/routes.ts')).not.toMatch(/path: '\/explorer'/)

    const nav = readFile(fixture.dir, 'src/constants/navigation.tsx')
    // The NAV_ICONS map entry is gone…
    expect(nav).not.toMatch(/\[ROUTE_PATHS\.EXPLORER\]/)
    // …but the icon import + DEFAULT_NAV_ICON usage survive (still used elsewhere).
    expect(nav).toMatch(/^\s*ExplorerNavIcon,\s*$/m)
    expect(nav).toMatch(/DEFAULT_NAV_ICON[^\n]*<ExplorerNavIcon \/>/)
  })

  it('remove page PoolManager deletes the page and unregisters route + nav icon', () => {
    const routes = EMPTY_ROUTES.replace(
      '  // mdk:routes-end',
      "  { path: '/pool-manager', label: 'Pool Manager', page: () => import('./pages/PoolManager') },\n  // mdk:routes-end",
    )
    const nav = EMPTY_NAV.replace(
      '  // mdk:nav-icons-end',
      '  PoolManagerNavIcon,\n  // mdk:nav-icons-end',
    ).replace('  // mdk:nav-end', "  '/pool-manager': <PoolManagerNavIcon />,\n  // mdk:nav-end")
    seedShell(fixture.dir, routes, nav)

    const pageDir = join(fixture.dir, 'src', 'pages')
    mkdirSync(pageDir, { recursive: true })
    writeFileSync(
      join(pageDir, 'PoolManager.tsx'),
      '/**\n * generated by `mdk-ui add page`\n */\nexport default function PoolManagerPage() { return null }\n',
      'utf8',
    )

    runRemovePage({ pageName: 'PoolManager', outDir: 'src/pages', cwd: fixture.dir, out: noop })

    expect(existsSync(join(pageDir, 'PoolManager.tsx'))).toBe(false)
    expect(readFile(fixture.dir, 'src/routes.ts')).not.toMatch(/path: '\/pool-manager'/)
    const navAfter = readFile(fixture.dir, 'src/constants/navigation.tsx')
    expect(navAfter).not.toMatch(/PoolManagerNavIcon/)
  })

  it('add → remove → add round-trips Alerts cleanly', () => {
    seedShell(fixture.dir)
    const opts = {
      packageName: '@tetherto/mdk-react-devkit',
      pageName: 'Alerts',
      outDir: 'src/pages',
      cwd: fixture.dir,
      out: noop,
    }

    runAddPage(opts)
    runRemovePage({ pageName: 'Alerts', outDir: 'src/pages', cwd: fixture.dir, out: noop })

    expect(existsSync(join(fixture.dir, 'src/pages/Alerts.tsx'))).toBe(false)
    expect(readFile(fixture.dir, 'src/constants/navigation.tsx')).not.toMatch(/AlertsNavIcon/)
    expect(readFile(fixture.dir, 'src/routes.ts')).not.toMatch(/path: '\/alerts'/)

    // Re-add restores everything without --force (file was removed).
    runAddPage(opts)
    expect(existsSync(join(fixture.dir, 'src/pages/Alerts.tsx'))).toBe(true)
    expect(readFile(fixture.dir, 'src/constants/navigation.tsx')).toMatch(/<AlertsNavIcon \/>/)
    expect(readFile(fixture.dir, 'src/routes.ts')).toMatch(/path: '\/alerts'/)
  })

  it('add → remove → add round-trips PoolManager cleanly', () => {
    seedShell(fixture.dir)
    const opts = {
      packageName: '@tetherto/mdk-react-devkit',
      pageName: 'PoolManager',
      outDir: 'src/pages',
      cwd: fixture.dir,
      out: noop,
    }

    runAddPage(opts)
    runRemovePage({ pageName: 'PoolManager', outDir: 'src/pages', cwd: fixture.dir, out: noop })

    expect(existsSync(join(fixture.dir, 'src/pages/PoolManager.tsx'))).toBe(false)
    expect(readFile(fixture.dir, 'src/constants/navigation.tsx')).not.toMatch(/PoolManagerNavIcon/)
    expect(readFile(fixture.dir, 'src/routes.ts')).not.toMatch(/path: '\/pool-manager'/)

    runAddPage(opts)
    expect(existsSync(join(fixture.dir, 'src/pages/PoolManager.tsx'))).toBe(true)
    expect(readFile(fixture.dir, 'src/constants/navigation.tsx')).toMatch(/<PoolManagerNavIcon \/>/)
    expect(readFile(fixture.dir, 'src/routes.ts')).toMatch(/path: '\/pool-manager'/)
  })

  it('re-adding an existing managed page refuses to overwrite without --force', () => {
    seedShell(fixture.dir)
    const opts = {
      packageName: '@tetherto/mdk-react-devkit',
      pageName: 'PoolManager',
      outDir: 'src/pages',
      cwd: fixture.dir,
      out: noop,
    }
    runAddPage(opts)
    expect(() => runAddPage(opts)).toThrow(/already exists/)
  })

  it('re-adding with --force keeps the route + nav registered exactly once (idempotent patch)', () => {
    seedShell(fixture.dir)
    const opts = {
      packageName: '@tetherto/mdk-react-devkit',
      pageName: 'PoolManager',
      outDir: 'src/pages',
      cwd: fixture.dir,
      force: true,
      out: noop,
    }
    runAddPage(opts)
    runAddPage(opts)

    const routes = readFile(fixture.dir, 'src/routes.ts')
    const nav = readFile(fixture.dir, 'src/constants/navigation.tsx')
    expect(routes.match(/path: '\/pool-manager'/g)).toHaveLength(1)
    expect(nav.match(/<PoolManagerNavIcon \/>/g)).toHaveLength(1)
    expect(nav.match(/^\s*PoolManagerNavIcon,\s*$/gm)).toHaveLength(1)
  })
})
