import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { afterEach, beforeEach, describe, expect, it } from 'vitest'

import { makeConsumerFixture, noop } from '../test-utils.js'
import { runRemovePage } from './remove-page.js'

/** Write a generated page file with the marker that `remove-page` recognises. */
const writeGeneratedPage = (dir: string, outDir: string, pageName: string): string => {
  const targetDir = join(dir, outDir)
  mkdirSync(targetDir, { recursive: true })
  const filePath = join(targetDir, `${pageName}.tsx`)
  writeFileSync(
    filePath,
    `/**\n * ${pageName}Page — generated by \`mdk-ui add page\`.\n */\nexport default function ${pageName}Page() { return null; }\n`,
    'utf8',
  )
  return filePath
}

/** Write a hand-edited page file with no generator marker. */
const writeManualPage = (dir: string, outDir: string, pageName: string): string => {
  const targetDir = join(dir, outDir)
  mkdirSync(targetDir, { recursive: true })
  const filePath = join(targetDir, `${pageName}.tsx`)
  writeFileSync(filePath, `export default function ${pageName}Page() { return null; }\n`, 'utf8')
  return filePath
}

describe('runRemovePage', () => {
  let fixture: ReturnType<typeof makeConsumerFixture>
  beforeEach(() => {
    fixture = makeConsumerFixture()
  })
  afterEach(() => fixture.dispose())

  it('removes a generated page file', () => {
    const filePath = writeGeneratedPage(fixture.dir, 'src/pages', 'MyPage')

    runRemovePage({
      pageName: 'MyPage',
      outDir: 'src/pages',
      cwd: fixture.dir,
      out: noop,
    })

    expect(existsSync(filePath)).toBe(false)
  })

  it('also removes the route entry from a routes file when present', () => {
    writeGeneratedPage(fixture.dir, 'src/pages', 'Dashboard')

    // Create a routes file with a route for this page (lowercase, no "page" suffix)
    const routesPath = join(fixture.dir, 'src', 'routes.ts')
    writeFileSync(
      routesPath,
      `export const ROUTES = [\n  { path: '/dashboard', label: 'Dashboard', page: () => import('./pages/Dashboard') },\n  // mdk:routes-end\n];\n`,
      'utf8',
    )

    const lines: string[] = []
    runRemovePage({
      pageName: 'Dashboard',
      outDir: 'src/pages',
      cwd: fixture.dir,
      out: (l) => lines.push(l),
    })

    const routeContent = readFileSync(routesPath, 'utf8')
    expect(routeContent).not.toMatch(/path: '\/dashboard'/)
    expect(lines.some((l) => l.includes('Removed route'))).toBe(true)
  })

  it('throws when the target file does not exist', () => {
    expect(() =>
      runRemovePage({
        pageName: 'NonExistent',
        outDir: 'src/pages',
        cwd: fixture.dir,
        out: noop,
      }),
    ).toThrow(/does not exist/)
  })

  it('throws for a modified file without --force', () => {
    writeManualPage(fixture.dir, 'src/pages', 'ManualPage')

    expect(() =>
      runRemovePage({
        pageName: 'ManualPage',
        outDir: 'src/pages',
        cwd: fixture.dir,
        out: noop,
      }),
    ).toThrow(/modified/)
  })

  it('deletes a modified file when force: true', () => {
    const filePath = writeManualPage(fixture.dir, 'src/pages', 'ForcedPage')

    runRemovePage({
      pageName: 'ForcedPage',
      outDir: 'src/pages',
      cwd: fixture.dir,
      force: true,
      out: noop,
    })

    expect(existsSync(filePath)).toBe(false)
  })
})
