import { existsSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

import { findManagedPage } from '../managed-pages.js'
import { unpatchNavIcon } from '../nav.js'
import { findRoutesFile } from '../routes-file.js'
import { toPascalCase } from '../utils.js'

export type RemovePageOptions = {
  pageName: string
  outDir: string
  cwd: string
  force?: boolean
  out?: (line: string) => void
}

// Matches both `add page` and `add feature` generator markers
const GENERATED_MARKER_RE = /generated by `mdk-ui add (?:page|feature)/

/**
 * Remove a route entry from the project's routes manifest (the reverse of
 * `patchRoutesFile` in add-page.ts). No-op when the routes file is absent
 * or the route path is not registered.
 */
const unpatchRoutesFile = (cwd: string, routePath: string, out: (line: string) => void): void => {
  const routesFile = findRoutesFile(cwd)
  if (!routesFile) return

  const content = readFileSync(routesFile, 'utf8')
  const lines = content.split('\n')
  const filtered = lines.filter((line) => {
    const trimmed = line.trim()
    if (!trimmed.startsWith('{') || !trimmed.includes('path:')) return true
    return !(trimmed.includes(`path: '${routePath}'`) || trimmed.includes(`path: "${routePath}"`))
  })

  if (filtered.length === lines.length) return

  writeFileSync(routesFile, filtered.join('\n'), 'utf8')
  out(`✓ Removed route ${routePath} from ${routesFile}`)
}

export const runRemovePage = (opts: RemovePageOptions): void => {
  const out =
    opts.out ??
    ((s: string) => {
      // eslint-disable-next-line no-console
      console.log(s)
    })

  // Managed pages (Pool Manager, Alerts) resolve their canonical name/route
  // regardless of how the command was typed, and also own a nav-icon entry.
  const managed = findManagedPage(opts.pageName)
  const pagePascal = managed?.name ?? toPascalCase(opts.pageName)
  const fileName = `${pagePascal}.tsx`
  const targetDir = resolve(opts.cwd, opts.outDir)
  const targetPath = join(targetDir, fileName)

  if (!existsSync(targetPath)) {
    throw new Error(`${targetPath} does not exist.`)
  }

  const contents = readFileSync(targetPath, 'utf8')
  if (!GENERATED_MARKER_RE.test(contents) && !opts.force) {
    throw new Error(`${fileName} has been modified. Re-run with --force to delete it anyway.`)
  }

  unlinkSync(targetPath)
  out(`✓ Deleted ${targetPath}`)

  const routePath = managed?.routePath ?? `/${pagePascal.replace(/Page$/, '').toLowerCase()}`
  unpatchRoutesFile(opts.cwd, routePath, out)

  if (managed) unpatchNavIcon(opts.cwd, managed, out)
}
